[project]
name = "piano-lessons"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mido>=1.3.3",
    "requests>=2.32.5",
]
